export const images = {
  LogoEve: require('./LogoEve.png'),
  LogoGuardian: require('./logoGuardian.png'),
  CloseEye: require('./close-eye.png'),
  ViewEye: require('./view_eye.png'),
  DiscIcon: require('./DiscIcon.png'),
  PopularEvent: require('./popularEvent.png'),
  Event1: require('./event1.png'),
  Event2: require('./event2.png'),
  Event3: require('./event3.png'),
  User1: require('./user1.png'),
  User2: require('./user2.png'),
  User3: require('./user3.png'),
  User4: require('./user4.png'),
  User5: require('./user5.png'),
  User6: require('./user6.png'),
  User7: require('./user7.png'),
  TicketIcon: require('./ticketIcon.png'),
  Map: require('./map.png'),
  VipIcon: require('./VipIcon.png'),
};
